# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92430110420409af32f0e938b369a5f834f845c0e3832ace7bbdd622e57d7863a7c0f7e9e2f2ff68bdd21eac778bfa78987565c21c26fc90af79bb4d5c0c133c

test:
  secret_key_base: 8bdfc8f7b297747ba965719a97b79e3d477f2d0827c5189c3603401b78e1e488d03a0a5c17343061784723a358de75bb85f440d5c24517a9e03def3c03f56b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
